<?xml version="1.0"?>
<package format="2">
    <name>legged_m2</name>
    <version>0.0.0</version>
    <description>ROS control based interface for xTerra Svan M2</description>
    <maintainer email="nimesh6798@gmail.com">Nimesh Khandelwal</maintainer>

    <license>BSD</license>
    <author email="nimesh6798@gmail.com">Nimesh Khandelwal</author>

    <buildtool_depend>catkin</buildtool_depend>

    <build_depend>cmake_clang_tools</build_depend>
    <depend>roscpp</depend>
    <depend>legged_hw</depend>
</package>
